esphome:
  name: esphome-web-0d05ec
  friendly_name: Pico Display
  min_version: 2025.11.0
  name_add_mac_suffix: false

rp2040:
  board: rpipicow

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  - id: i2c_bus0
    sda: GPIO6
    scl: GPIO7
    frequency: 100kHz
    scan: true

spi:
  - id: spi_bus0
    clk_pin: GPIO10
    mosi_pin: GPIO11
    miso_pin: GPIO12

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic

  - platform: gpio
    pin:
      number: GPIO26
      mode:
        input: true
        pullup: true
    name: "mmWave Sensor"
    id: mmwave

sensor:
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    entity_category: diagnostic
    internal: true

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  - platform: wifi_signal
    name: "WiFi Strength"
    id: wifi_strength
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic

time:
  - platform: homeassistant
    id: esptime

font:
  - file: "fonts/ocraext.ttf"
    id: font1
    size: 14
  - file: "fonts/ocraext.ttf"
    id: fontocra
    size: 32
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: mdi_42
    size: 42
    bpp: 4
    glyphs:
      - "\U000F0335"
      - "\U000F0336"

touchscreen:
  - platform: cst816
    id: my_touch
    display: my_display
    skip_probe: true
    interrupt_pin:
      number: GPIO8
      mode: INPUT_PULLUP
    on_touch:
      - lambda: |-
          ESP_LOGI("touch", "Touch registered at X=%d, Y=%d", touch.x, touch.y);

display:
  - platform: st7789v
    id: my_display
    model: Custom
    width: 240
    height: 320
    offset_width: 0
    offset_height: 0
    cs_pin: GPIO9
    dc_pin: GPIO14
    reset_pin: GPIO13
    backlight_pin: GPIO15
    rotation: 0
    update_interval: 1s
    show_test_card: false
    lambda: |-
      it.fill(Color(0, 0, 0));

      it.print(10, 10, id(font1), Color(255, 255, 255), "PICO MONITOR");
      it.line(10, 30, 230, 30, Color(0, 0, 255));

      if (id(mmwave).state) {
        it.print(10, 50, id(fontocra), Color(255, 0, 0), "MOTION");
      } else {
        it.print(10, 50, id(fontocra), Color(0, 255, 0), "CLEAR");
      }

      it.printf(10, 120, id(font1), Color(255, 255, 255), "WiFi: %.0f%%", id(wifi_strength).state);
      it.printf(10, 150, id(font1), Color(255, 255, 255), "Uptime: %.0fs", id(uptime_sensor).state);
